/**
 * Workflow Module - Hook Registration
 *
 * Registers lifecycle hooks for:
 * - Auto-enrolling contacts in event-triggered workflows
 * - Checking exit conditions when activities complete
 */

import { hooks } from '../../core/hooks.js';
import { db } from '../../core/db.js';
import { DataRecord, DataRecordInput } from '../../core/types.js';
import { WorkflowEngine } from './engine.js';

/**
 * Auto-enroll contacts in workflows on creation
 */
hooks.onPostCreate('contact', async (record: DataRecordInput | DataRecord) => {
    if (!(record as DataRecord).id) return;

    try {
        await WorkflowEngine.checkAndEnroll(record as DataRecord, 'contact_created');
    } catch (err) {
        console.warn(`[Workflows] Failed to check workflow enrollment on contact creation: ${err instanceof Error ? err.message : String(err)}`);
    }
});

/**
 * Check for form submission trigger
 */
hooks.onPostCreate('activity', async (record: DataRecordInput | DataRecord) => {
    const data = record.data as Record<string, any>;

    // Check if this is a form submission activity
    if (data?.activity_def_slug === 'form_submitted') {
        const contactId = data?.contact_id;
        if (!contactId) return;

        try {
            // Get the contact record
            const contact = db.prepare('SELECT * FROM records WHERE id = ?').get(contactId) as DataRecord | undefined;
            if (contact) {
                if (typeof contact.data === 'string') {
                    contact.data = JSON.parse(contact.data);
                }
                await WorkflowEngine.checkAndEnroll(contact, 'form_submitted');
            }
        } catch (err) {
            console.warn(`[Workflows] Failed to check workflow enrollment on form submission: ${err instanceof Error ? err.message : String(err)}`);
        }
    }
});

/**
 * Check exit conditions when activities complete
 * If an activity generated by a workflow is completed, check if it triggers workflow exit
 */
hooks.onPostUpdate('activity', async (record: DataRecordInput | DataRecord) => {
    const data = record.data as Record<string, any>;

    // Only check on activity completion
    if (data?.status !== 'completed') return;

    const enrollmentId = data?.workflow_enrollment_id;
    if (!enrollmentId) return;

    try {
        // Get the enrollment
        const enrollment = db.prepare('SELECT * FROM records WHERE id = ?').get(enrollmentId) as DataRecord | undefined;
        if (!enrollment) return;

        if (typeof enrollment.data === 'string') {
            enrollment.data = JSON.parse(enrollment.data);
        }

        // Check if enrollment is still active
        if (enrollment.data?.status !== 'active') return;

        // Get the workflow to check exit conditions
        const workflowId = enrollment.data?.workflow_id;
        if (!workflowId) return;

        const workflow = db.prepare('SELECT * FROM records WHERE id = ?').get(workflowId) as DataRecord | undefined;
        if (!workflow) return;

        if (typeof workflow.data === 'string') {
            workflow.data = JSON.parse(workflow.data);
        }

        // Check exit conditions from workflow
        const exitConditions = workflow.data?.exit_conditions;
        if (!exitConditions || !Array.isArray(exitConditions) || exitConditions.length === 0) return;

        // Get contact to evaluate conditions
        const contactId = enrollment.data?.contact_id;
        if (!contactId) return;

        const contact = db.prepare('SELECT * FROM records WHERE id = ?').get(contactId) as DataRecord | undefined;
        if (!contact) return;

        if (typeof contact.data === 'string') {
            contact.data = JSON.parse(contact.data);
        }

        // Simple qualifier evaluation
        const allConditionsMet = exitConditions.every((qualifier: any) => {
            // For now, just check if the qualifier field has a value
            // Full qualifier evaluation should use the same logic as chain_reaction.ts
            const qualifierPath = qualifier.qualifier;
            if (!qualifierPath) return false;

            // Check if qualifier has been evaluated
            return qualifier._evaluated === true && qualifier._result === true;
        });

        if (allConditionsMet) {
            console.log(`[Workflows] Exit conditions met for enrollment ${enrollmentId}, completing workflow`);
            await WorkflowEngine.completeEnrollment(enrollmentId, 'win');
        }
    } catch (err) {
        console.warn(`[Workflows] Failed to check workflow exit conditions: ${err instanceof Error ? err.message : String(err)}`);
    }
});

// Re-export for convenience
export { WorkflowEngine } from './engine.js';
export { startWorkflowScheduler, stopWorkflowScheduler, isWorkflowSchedulerRunning, triggerWorkflowProcessing } from './scheduler.js';
export { executeStepHandler } from './handlers.js';
