-- Universal Schema (VI v5 / Oblio)
-- Generated by Schema Alignment Migration

-- 1. Identity & Tenancy

-- Users (for ODAC authentication)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  name TEXT,
  avatar_url TEXT,
  global_preferences JSON DEFAULT '{}',
  primary_account_id TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  deleted_at TEXT
);

-- Accounts (organizational units)
CREATE TABLE IF NOT EXISTS accounts (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  account_class TEXT NOT NULL DEFAULT 'business',
  type TEXT DEFAULT 'client',
  data JSON DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  deleted_at TEXT
);

-- User-Account membership (legacy - ODAC derives from opportunities)
CREATE TABLE IF NOT EXISTS user_accounts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  permission_level TEXT DEFAULT 'viewer',
  role_overrides JSON DEFAULT '{}',
  data JSON DEFAULT '{}',
  is_active INTEGER DEFAULT 1,
  joined_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  UNIQUE(user_id, account_id)
);



-- 2. Records (Catalog & Content) - Renamed from Entities
CREATE TABLE IF NOT EXISTS records (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL, -- Partition Key (Logical reference)
  type TEXT NOT NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  summary TEXT,
  description TEXT,
  data JSON DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  deleted_at TEXT,
  content_hash TEXT,
  UNIQUE(account_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_records_type ON records(type);

CREATE TABLE IF NOT EXISTS record_relationships (
  id TEXT PRIMARY KEY,
  from_record_id TEXT NOT NULL,
  to_record_id TEXT NOT NULL,
  relationship_type TEXT NOT NULL,
  data JSON DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (from_record_id) REFERENCES records(id) ON DELETE CASCADE,
  FOREIGN KEY (to_record_id) REFERENCES records(id) ON DELETE CASCADE,
  UNIQUE(from_record_id, to_record_id, relationship_type)
);

CREATE INDEX IF NOT EXISTS idx_rels_from ON record_relationships(from_record_id);
CREATE INDEX IF NOT EXISTS idx_rels_to ON record_relationships(to_record_id);
CREATE INDEX IF NOT EXISTS idx_rels_type ON record_relationships(relationship_type);


-- 3. System & Configuration
CREATE TABLE IF NOT EXISTS dimension_values (
  id TEXT PRIMARY KEY,
  dimension TEXT NOT NULL,
  slug TEXT NOT NULL,
  label TEXT NOT NULL,
  parent_id TEXT,
  account_id TEXT, -- NULL = Global
  metadata JSON DEFAULT '{}',
  source TEXT DEFAULT 'manual',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES dimension_values(id),
  FOREIGN KEY (account_id) REFERENCES records(id),
  UNIQUE(dimension, slug, account_id)
);

CREATE INDEX IF NOT EXISTS idx_dimval_dimension ON dimension_values(dimension);

-- Phase 4: Dimension Dependencies (Cascading Pick-lists)
-- Models cross-dimension relationships for interdependent filtering
-- Example: Department <-> Job Title, Sector <-> Industry
CREATE TABLE IF NOT EXISTS dimension_dependencies (
  id TEXT PRIMARY KEY,
  source_dimension TEXT NOT NULL,
  source_value_id TEXT NOT NULL,
  target_dimension TEXT NOT NULL,
  target_value_id TEXT NOT NULL,
  bidirectional INTEGER DEFAULT 1,
  weight INTEGER DEFAULT 100,
  metadata JSON DEFAULT '{}',
  account_id TEXT,
  source TEXT DEFAULT 'manual',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (source_value_id) REFERENCES dimension_values(id) ON DELETE CASCADE,
  FOREIGN KEY (target_value_id) REFERENCES dimension_values(id) ON DELETE CASCADE,
  UNIQUE(source_value_id, target_value_id, account_id)
);

CREATE INDEX IF NOT EXISTS idx_dimdep_source ON dimension_dependencies(source_dimension, source_value_id);
CREATE INDEX IF NOT EXISTS idx_dimdep_target ON dimension_dependencies(target_dimension, target_value_id);

CREATE TABLE IF NOT EXISTS page_templates (
  id TEXT PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  subject_target TEXT,
  subject_cardinality TEXT,
  sections JSON DEFAULT '[]',
  content_hash TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- 5. Infrastructure
CREATE TABLE IF NOT EXISTS domains (
  id TEXT PRIMARY KEY,
  account_id TEXT NOT NULL, -- Replaces brand_id
  hostname TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL DEFAULT 'www',
  is_primary INTEGER DEFAULT 0,
  config JSON DEFAULT '{}',
  entity_types JSON DEFAULT '[]',
  status TEXT DEFAULT 'active',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES records(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS build_state (
  record_id TEXT PRIMARY KEY,
  content_hash TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  last_built_at TEXT,
  error TEXT,
  FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS _migrations (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  applied_at TEXT DEFAULT CURRENT_TIMESTAMP
);
